### ISSUE TITLE
[resize-observer] v2.x Error rendering in RTL/jest-dom: TypeError: (e || window.ResizeObserver) is not a constructor

### ISSUE THREAD

**Issue by jbaldassari** [jaredLunde/react-hook#308]
**Describe the bug**
Since upgrading from v1.2.6 to v2.0.1, all react `testing-library` unit tests that render `useResizeObserver` are failing with this error:

```
Error: Uncaught [TypeError: (e || window.ResizeObserver) is not a constructor]
    at createResizeObserver (file://./node_modules/.pnpm/registry.npmjs.org+@react-hook+resize-observer@2.0.1_react@18.3.1/node_modules/@react-hook/resize-observer/src/index.tsx:49:20)
    at getResizeObserver (file://./node_modules/.pnpm/registry.npmjs.org+@react-hook+resize-observer@2.0.1_react@18.3.1/node_modules/@react-hook/resize-observer/src/index.tsx:95:26)
    at Module.r (file://./node_modules/.pnpm/registry.npmjs.org+@react-hook+resize-observer@2.0.1_react@18.3.1/node_modules/@react-hook/resize-observer/src/index.tsx:19:26)
    ....
    at renderWithHooks (./node_modules/.pnpm/registry.npmjs.org+react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:15486:18)
    at updateFunctionComponent (./node_modules/.pnpm/registry.npmjs.org+react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:19617:20)
    at mountLazyComponent (./node_modules/.pnpm/registry.npmjs.org+react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:19988:17)
    at beginWork (./node_modules/.pnpm/registry.npmjs.org+react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:21632:16)
```

The call it's complaining about in `createResizeObserver` seems to have changed here: https://github.com/jaredLunde/react-hook/commit/80d260a2a2ad67b52cf828a15c2a2dadbbc417e5

When rendering in a normal browser there is no error, so I'm guessing that this is due to a difference in `@testing-library/jest-dom`.

**To Reproduce**
1. Render a component that calls `useResizeObserver` inside a react `testing-library` test.
2. Observe that component fails to render with uncaught exception above

If it would be helpful, I could try to put together a reproduction case somewhere.

**Expected behavior**
Renders without error in RTL unit tests, as it did prior to v2.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: vitest, RTL/jest-dom
 - Version: 6.4.5

**Comment by jaredLunde** [comment]
yes, v2 removes the polyfill so it's your responsibility to add one if you need it

**Comment by jbaldassari** [comment]
@jaredLunde thanks for the tip.  I ended up using `@juggle/resize-observer` as a polyfill similar to how `useResizeObserver` used to do it.  In case this is helpful to anyone else, it looks something like this:

```
import {ResizeObserver as ResizeObserverPolyfill} from '@juggle/resize-observer';

const polyfill =
  typeof window !== 'undefined' && 'ResizeObserver' in window
    ? undefined // No polyfill needed if ResizeObserver API is supported by browser
    : ResizeObserverPolyfill;

useResizeObserver(target, (entry) => yourEventHandler(entry), {polyfill});
```
